transifex/transifex-delivery

Makefile
Remove the `TARGET_TAG` variable from the Makefile commands
`build` and `build_prod`. This allows to pass a custom `TARGET_TAG`
when building the image. It still defaults to `latest`.
=> Small Makefile fixup

README.md, src/middlewares/headers.js, src/queue/worker.js, src/routes/analytics.js, src/routes/content.js, src/routes/invalidate.js, src/routes/languages.js, src/services/registry/index.js, tests/routes/analytics.spec.js, tests/routes/invalidate.spec.js, tests/services/registry.spec.js
It seems that Python Native SDK is hitting aggressively CDS creating false positives on the traffic of the service.
This PR updates analytics to track the hits of unique visitors per day instead of actual page hits.
It also fixes an issue with secret key authentication both on analytics and invalidate endpoints. From now on, a successful push of source content is required in order for credentials to be stored in CDS and then subsequently be used for invalidation and analytics.
=> Analytics v2

.github/workflows/tests.yml, Makefile, README.md, package.json, src/services/syncer/strategies/transifex/utils/transformer.js, tests/services/syncer/strategies/transifex/helpers/api.js, tests/services/syncer/strategies/transifex/utils/transformer.spec.js
Make `parseSourceStringForAPI` work with string.
The change takes place due to the work in [api-v3](https://github.com/transifex/transifex-api-v3/pull/436) where the `context` attribute's type from `list` to `string`.
=> Make `parseSourceStringForAPI` work with string

README.md, config/defaults.yml, config/test.yml, src/middlewares/headers.js, src/routes/analytics.js, src/routes/invalidate.js, src/routes/purge.js, tests/routes/analytics.spec.js, tests/routes/invalidate.spec.js, tests/routes/purge.spec.js
Add a way to invalidate cache and get analytics data from CDS by trusting credentials between Transifex and CDS.
=> Add trust secret authentication

README.md, src/helpers/validators.js, src/services/syncer/strategies/transifex/utils/api.js, src/services/syncer/strategies/transifex/utils/api_payloads.js
- Update push source content to append tags to existing string instead of replacing them
- Update patch Transifex strategy to properly detect if a string is eligible for update, skip otherwise
=> Append tags to existing strings by default

README.md, config/defaults.yml, src/index.js
This adds a new setting `settings:keep_alive_timeout` or
`TX__SETTINGS__KEEP_ALIVE_TIMEOUT_SEC` that if it is different than the
default value `''` adds a keepAliveTimeout setting to the node server.
This can be really helpful in situations that there is a load balancer
in front of the application and this setting needs to be a bit higher
than the load balancer's idle timeout.
=> Provide keepAliveTimeout setting for the app

src/services/syncer/strategies/transifex/utils/api.js, src/services/syncer/strategies/transifex/utils/api_urls.js, tests/routes/content.spec.js, tests/routes/languages.spec.js, tests/services/syncer/strategies/transifex/data.spec.js
When not purging during push, detect the minimum requests required to get current content before comparing it with content to be pushed using the following two strategies:
1. Get the whole resource strategy, getting all strings in batches of 1000
2. Query specific keys
For example, pushing 10 strings in a resource of 150K strings would require the following requests:
1. 150 requests to get the whole resource
2. 10 requests to get the status the 10 strings
So in that case, the second strategy would be used.
=> Detect optimal push strategy based on content

src/services/syncer/strategies/transifex/utils/api_urls.js, tests/routes/content.spec.js, tests/services/syncer/strategies/transifex/data.spec.js, tests/services/syncer/strategies/transifex/utils/api_urls.spec.js
Gets resource translations with a limit of 1000 instead of 150 for performance reasons.
=> Add limit in resource translations

README.md, config/defaults.yml, package-lock.json, package.json, src/middlewares/headers.js, src/queue/index.js, src/queue/worker.js, src/routes/content.js, src/routes/invalidate.js, src/routes/jobs.js, src/routes/purge.js, src/server.js, src/services/syncer/data.js, src/services/syncer/strategies/transifex/utils/api.js, tests/routes/analytics.spec.js, tests/routes/content.spec.js, tests/routes/invalidate.spec.js, tests/routes/languages.spec.js, tests/routes/purge.spec.js, tests/services/cache/route.spec.js, tests/services/syncer/strategies/transifex/data.spec.js
Introduces async source content uploads.
To ensure compatibility with existing SDKs, the `Accept-version` header is introduced and the API is officially migrated to `v2`, with the old version entering a deprecation mode, to be totally removed in `1.0.0` release of the service.
Changes:
- Enable API versioning via `Accept-version` header
- Update `/health` endpoint response with more info on workers
- Update `POST /content` response
- Add `GET /jobs/content/id` endpoint for polling workers
- Update `/invalidate` and `/purge` responses
- Bump packages
=> Enable async content upload

src/middlewares/metrics.js, src/server.js
Add the following Prometheus custom metrics:
- jobs_waiting
- jobs_active
- jobs_delayed
which can be used by any external system (ex. Kubernetes) for scaling purposes.
=> Add custom prometheus metrics for worker tasks

src/middlewares/metrics.js
Add environment info in the naming to differentiate multiple environments.
=> Modify naming convention to prometheus metrics

README.md, package-lock.json, package.json, src/queue/index.js, src/routes/content.js
Fixes unused Redis job-ID keys being created that would never resolve when pushing the same content.
=> Add HTTP 409 response on POST /content

config/defaults.yml, package-lock.json, package.json, src/queue/index.js, src/queue/worker.js
When Transifex is down (e.g. during maintenance windows), the APIv3 endpoints return `503` status code.
This case was not properly covered by the workers and the failed jobs (e.g. pull or push content) could not gracefully fail, leaving the job status in a zombie state.
As a side effect, hitting `/languages` or `/content` endpoints could end-up in an infinite `202` response (job in progress, try again later).
With this fix, a failed job will properly set it's status to `fail`, so that CDS endpoints status code could eventually stop looping forever.
=> Gracefully abort failed jobs

package-lock.json, package.json, src/helpers/utils.js, src/queue/worker.js
Avoid overriding a successful previous cache state, with a failed one.
=> Improve worker error handling

README.md, src/helpers/validators.js, src/services/syncer/data.js, src/services/syncer/strategies/transifex/utils/api.js, tests/services/syncer/strategies/transifex/data.spec.js
Add support for emulating content push (dry run), so that SDKs can check which strings will be created, updated, deleted or skipped, in relation to the actual content in Transifex.
=> Add support for dry-run when pushing content

README.md, src/routes/content.js, src/routes/invalidate.js, src/services/syncer/data.js, src/services/syncer/strategies/transifex/data.js, src/services/syncer/strategies/transifex/utils/api.js, src/services/syncer/strategies/transifex/utils/api_urls.js
Add support for filtering content to be fetched by translation status:
```
GET /content/<lang-code>?filter[status]=translated|reviewed|proofread|finalized
```
Backend implementation works in par with [Transifex APIv3](https://developers.transifex.com/reference/get_resource-translations).
=> Add filter[status] support to get content endpoint

src/helpers/languages.js
I updated the text displayed on the language picker for zh-Hant and zh-Hans languages. The previous translation was not natural for native language speakers.
=> TX-14726 - changes to zh-Hant and zh-Hans text in language picker

README.md, src/helpers/validators.js, src/queue/worker.js, tests/routes/content.spec.js
Update response status when polling for the status of a failed push job, so that it is uniform to the Transifex APIv3 error format.
=> Update worker error status

README.md, src/helpers/validators.js, src/services/syncer/data.js, src/services/syncer/strategies/transifex/utils/api.js, src/services/syncer/strategies/transifex/utils/api_payloads.js
By default merge occurrences of a string, similar to the way `tags` work.
If `override_occurrences` is set in the `POST /content` metadata, then override target occurrences.
=> Add support for appending occurrences

src/middlewares/metrics.js
/metrics on web pod
```
process_cpu_user_seconds_total{application="transifex-delivery",environment="beta"} 13.413768000000006
process_cpu_system_seconds_total{application="transifex-delivery",environment="beta"} 3.098908999999999
process_cpu_seconds_total{application="transifex-delivery",environment="beta"} 16.51267699999999
process_start_time_seconds{application="transifex-delivery",environment="beta"} 1694523365
process_resident_memory_bytes{application="transifex-delivery",environment="beta"} 75350016
process_virtual_memory_bytes{application="transifex-delivery",environment="beta"} 733446144
process_heap_bytes{application="transifex-delivery",environment="beta"} 107737088
process_open_fds{application="transifex-delivery",environment="beta"} 31 …
```
=> Disable path and merge status codes in prom metrics

config/defaults.yml, src/helpers/utils.js, src/queue/worker.js
Content is cached in the service for about 1hour unless invalidated. There is already a function in place that if 1hour has elapsed, content will be refreshed.
This can cause some pressure to the system, so with this PR we are adding a random jitter in the auto-sync window to reduce chances that mass amount of content is refreshed at the same time.
=> Add jitter to autosync functionality

src/services/syncer/strategies/transifex/utils/api.js, src/services/syncer/strategies/transifex/utils/api_payloads.js, tests/services/syncer/strategies/transifex/data.spec.js
Related to [TX-15487: Add parameter "keep_translations"to the API endpoint "Update a resource string"](https://xtm-cloud.atlassian.net/browse/TX-15487)
Related PRs
[1# openai](https://github.com/transifex/openapi/pull/487)
[2# transifex-api-v3](https://github.com/transifex/transifex-api-v3/pull/1268)
We should allow the user when updating a source string to decide whether they want to keep or delete any existing translations.
Also this PR resolves the issue described [here](https://xtm-cloud.atlassian.net/browse/TX-16382).
> When the customer updates a source string via the SDK with --do-not-keep-translations flag, the system should discard the existing translations and reflect only the source change. Instead, the string history incorrectly shows translation actions (translated, reviewed, …
=> TX-15487: Pass keep_translations option to resource string request
